services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - API_HOST=localhost
        - API_PORT=8080
    ports:
      - $FE_PORT:80
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - $BE_PORT:8080
    environment:
      - PORT=8080
      - DB_HOST=postgresql
      - DB_PORT=5432
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:13
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/postgresql/data
